include_defs('//plugins/gerrit-owners/common.defs')

gerrit_plugin(
  name = 'owners-autoassign',
  srcs = glob([
    'src/main/java/**/*.java',
  ]),
  manifest_entries = [
    'Implementation-Title: Gerrit OWNERS autoassign plugin',
    'Implementation-URL: https://github.com/vadims/gerrit-owners',
    'Gerrit-PluginName: owners-autoassign',
  ],
  deps = [
    '//plugins/gerrit-owners/gerrit-owners-common:common',
  ] + EXTERNAL_DEPS,
)
