include_defs('//plugins/gerrit-owners/common.defs')

# see common.defs on why this is a java_library2 rather than java_library
java_library2(
  name = 'common',
  srcs = glob([
    'src/main/java/**/*.java',
  ]),
  deps = [],
  # Notice that we put EXTERNAL_DEPS as compile_deps to prevent double inclusion in the owners
  # plugin.
  compile_deps = COMPILE_DEPS + EXTERNAL_DEPS,
  visibility = ['PUBLIC'],
)
